/**
 * Key Mappings for Pokemon Key Migration
 * Maps old keys (name_formType) to new keys (stableId)
 * 
 * Auto-generated by generateKeyMappings.js
 */

import keyMappingsData from './keyMappings.json';

// Export the mappings
const keyMappings = keyMappingsData || {};

/**
 * Get the new key for an old key
 * @param {string} oldKey - Old key format: name_formType or name_formType_shiny
 * @returns {string|null} - New key with stableId, or null if no mapping exists
 */
export function getNewKey(oldKey) {
  return keyMappings[oldKey] || null;
}

/**
 * Get all key mappings
 * @returns {Object} - Object mapping old keys to new keys
 */
export function getAllMappings() {
  return { ...keyMappings };
}

/**
 * Add a key mapping
 * @param {string} oldKey - Old key
 * @param {string} newKey - New key (stableId)
 */
export function addMapping(oldKey, newKey) {
  keyMappings[oldKey] = newKey;
}

/**
 * Check if an old key has a mapping
 * @param {string} oldKey - Old key to check
 * @returns {boolean}
 */
export function hasMapping(oldKey) {
  return oldKey in keyMappings;
}

export default keyMappings;
