/**
 * Generate key mappings from Pokemon data
 * Creates a mapping file from old keys (name_formType) to new keys (stableId)
 * 
 * Usage: node scripts/generateKeyMappings.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function loadFormsData() {
  const formsDir = path.join(__dirname, '../src/data/forms');
  const formFiles = [
    'gender.json',
    'alolan.json',
    'galarian.json',
    'hisuian.json',
    'paldean.json',
    'gmax.json',
    'unown.json',
    'other.json',
    'alcremie.json',
    'vivillon.json',
    'alpha.json',
    'alphaother.json'
  ];
  
  const allForms = [];
  formFiles.forEach(file => {
    const filePath = path.join(formsDir, file);
    if (fs.existsSync(filePath)) {
      try {
        const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
        if (Array.isArray(data)) {
          allForms.push(...data);
        }
      } catch (error) {
        console.warn(`⚠️  Warning: Could not load ${file}:`, error.message);
      }
    }
  });
  
  return allForms;
}

function generateKeyMappings() {
  const formsData = loadFormsData();
  const pokemonData = JSON.parse(
    fs.readFileSync(path.join(__dirname, '../src/data/pokemon.json'), 'utf8')
  );
  
  const mappings = {};
  
  // Process main Pokemon (no formType)
  pokemonData.forEach(pokemon => {
    if (!pokemon.stableId || !pokemon.name) return;
    
    const name = pokemon.name.toLowerCase();
    
    // Regular
    const oldKey = name;
    mappings[oldKey] = pokemon.stableId;
    
    // Shiny
    mappings[`${oldKey}_shiny`] = `${pokemon.stableId}_shiny`;
  });
  
  // Process form Pokemon
  formsData.forEach(pokemon => {
    if (!pokemon.stableId || !pokemon.name || !pokemon.formType) return;
    
    const name = pokemon.name.toLowerCase();
    const formType = pokemon.formType;
    
    // Standard old format: name_formType
    const oldKey = `${name}_${formType}`;
    mappings[oldKey] = pokemon.stableId;
    mappings[`${oldKey}_shiny`] = `${pokemon.stableId}_shiny`;
    
    // Handle intermediate format: if name already contains formType (e.g., "exeggutor-alolan")
    // Create mapping for name_shiny -> stableId_shiny
    // This handles keys like "exeggutor-alolan_shiny" that are missing the _alolan suffix
    if (name.includes(`-${formType}`) || name.includes(`-${formType}s`)) {
      // Regular (intermediate format)
      mappings[name] = pokemon.stableId;
      // Shiny (intermediate format)
      mappings[`${name}_shiny`] = `${pokemon.stableId}_shiny`;
    }
  });
  
  return mappings;
}

function main() {
  console.log('🚀 Generating key mappings...\n');
  
  try {
    const mappings = generateKeyMappings();
    const outputPath = path.join(__dirname, '../src/utils/keyMappings.json');
    
    fs.writeFileSync(
      outputPath,
      JSON.stringify(mappings, null, 2)
    );
    
    // Also update the keyMappings.js file to import the JSON
    const keyMappingsJsPath = path.join(__dirname, '../src/utils/keyMappings.js');
    const keyMappingsJsContent = `/**
 * Key Mappings for Pokemon Key Migration
 * Maps old keys (name_formType) to new keys (stableId)
 * 
 * Auto-generated by generateKeyMappings.js
 */

import keyMappingsData from './keyMappings.json';

// Export the mappings
const keyMappings = keyMappingsData || {};

/**
 * Get the new key for an old key
 * @param {string} oldKey - Old key format: name_formType or name_formType_shiny
 * @returns {string|null} - New key with stableId, or null if no mapping exists
 */
export function getNewKey(oldKey) {
  return keyMappings[oldKey] || null;
}

/**
 * Get all key mappings
 * @returns {Object} - Object mapping old keys to new keys
 */
export function getAllMappings() {
  return { ...keyMappings };
}

/**
 * Add a key mapping
 * @param {string} oldKey - Old key
 * @param {string} newKey - New key (stableId)
 */
export function addMapping(oldKey, newKey) {
  keyMappings[oldKey] = newKey;
}

/**
 * Check if an old key has a mapping
 * @param {string} oldKey - Old key to check
 * @returns {boolean}
 */
export function hasMapping(oldKey) {
  return oldKey in keyMappings;
}

export default keyMappings;
`;
    
    fs.writeFileSync(keyMappingsJsPath, keyMappingsJsContent);
    
    console.log(`✅ Generated ${Object.keys(mappings).length} key mappings`);
    console.log(`📁 Saved mappings to: ${outputPath}`);
    console.log(`📁 Updated keyMappings.js to import from JSON`);
    console.log('\n⚠️  Next steps:');
    console.log('   1. Review the generated mappings');
    console.log('   2. Test the system with a Pokemon that has stableId');
    console.log('   3. Create migration script to update user data (optional)');
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
}

main();
