// BALLS
export const BALL_OPTIONS = [
  { name: "None", value: "" },
  { name: "Poké Ball", value: "Poké Ball", image: "/data/balls/poke-ball.png" },
  { name: "Great Ball", value: "Great Ball", image: "/data/balls/great-ball.png" },
  { name: "Ultra Ball", value: "Ultra Ball", image: "/data/balls/ultra-ball.png" },
  { name: "Master Ball", value: "Master Ball", image: "/data/balls/master-ball.png" },
  { name: "Safari Ball", value: "Safari Ball", image: "/data/balls/safari-ball.png" },
  { name: "Level Ball", value: "Level Ball", image: "/data/balls/level-ball.png" },
  { name: "Lure Ball", value: "Lure Ball", image: "/data/balls/lure-ball.png" },
  { name: "Moon Ball", value: "Moon Ball", image: "/data/balls/moon-ball.png" },
  { name: "Friend Ball", value: "Friend Ball", image: "/data/balls/friend-ball.png" },
  { name: "Love Ball", value: "Love Ball", image: "/data/balls/love-ball.png" },
  { name: "Heavy Ball", value: "Heavy Ball", image: "/data/balls/heavy-ball.png" },
  { name: "Fast Ball", value: "Fast Ball", image: "/data/balls/fast-ball.png" },
  { name: "Sport Ball", value: "Sport Ball", image: "/data/balls/sport-ball.png" },
  { name: "Premier Ball", value: "Premier Ball", image: "/data/balls/premier-ball.png" },
  { name: "Repeat Ball", value: "Repeat Ball", image: "/data/balls/repeat-ball.png" },
  { name: "Timer Ball", value: "Timer Ball", image: "/data/balls/timer-ball.png" },
  { name: "Nest Ball", value: "Nest Ball", image: "/data/balls/nest-ball.png" },
  { name: "Net Ball", value: "Net Ball", image: "/data/balls/net-ball.png" },
  { name: "Dive Ball", value: "Dive Ball", image: "/data/balls/dive-ball.png" },
  { name: "Luxury Ball", value: "Luxury Ball", image: "/data/balls/luxury-ball.png" },
  { name: "Heal Ball", value: "Heal Ball", image: "/data/balls/heal-ball.png" },
  { name: "Quick Ball", value: "Quick Ball", image: "/data/balls/quick-ball.png" },
  { name: "Dusk Ball", value: "Dusk Ball", image: "/data/balls/dusk-ball.png" },
  { name: "Cherish Ball", value: "Cherish Ball", image: "/data/balls/cherish-ball.png" },
  { name: "Dream Ball", value: "Dream Ball", image: "/data/balls/dream-ball.png" },
  { name: "Beast Ball", value: "Beast Ball", image: "/data/balls/beast-ball.png" },
  { name: "Feather Ball", value: "Feather Ball", image: "/data/balls/feather-ball.png" },
  { name: "Wing Ball", value: "Wing Ball", image: "/data/balls/wing-ball.png" },
  { name: "Jet Ball", value: "Jet Ball", image: "/data/balls/jet-ball.png" },
  { name: "Heavy Ball (Hisui)", value: "Heavy Ball (Hisui)", image: "/data/balls/hisui-heavy-ball.png" },
  { name: "Leaden Ball", value: "Leaden Ball", image: "/data/balls/leaden-ball.png" },
  { name: "Gigaton Ball", value: "Gigaton Ball", image: "/data/balls/gigaton-ball.png" },
  { name: "Poké Ball (Hisui)", value: "Poké Ball (Hisui)", image: "/data/balls/hisui-poke-ball.png" },
  { name: "Great Ball (Hisui)", value: "Great Ball (Hisui)", image: "/data/balls/hisui-great-ball.png" },
  { name: "Ultra Ball (Hisui)", value: "Ultra Ball (Hisui)", image: "/data/balls/hisui-ultra-ball.png" },
  { name: "Origin Ball", value: "Origin Ball", image: "/data/balls/origin-ball.png" },
  { name: "Strange Ball", value: "Strange Ball", image: "/data/balls/strange-ball.png" }
];

// GAMES
export const GAME_OPTIONS = [
  { name: "None", value: "" },

  // Gen 1 (1996–1999)
  { name: "Red", value: "Red", image: "/data/games/red.png" },
  { name: "Blue", value: "Blue", image: "/data/games/blue.png" },
  { name: "Green", value: "Green", image: "/data/games/green.png" },
  { name: "Yellow", value: "Yellow", image: "/data/games/yellow.png" },

  // Gen 2 (1999–2001)
  { name: "Gold", value: "Gold", image: "/data/games/gold.png" },
  { name: "Silver", value: "Silver", image: "/data/games/silver.png" },
  { name: "Crystal", value: "Crystal", image: "/data/games/crystal.png" },

  // Gen 3 (2002–2006)
  { name: "Ruby", value: "Ruby", image: "/data/games/ruby.png" },
  { name: "Sapphire", value: "Sapphire", image: "/data/games/sapphire.png" },
  { name: "Emerald", value: "Emerald", image: "/data/games/emerald.png" },
  { name: "Fire Red", value: "Fire Red", image: "/data/games/fire-red.png" },
  { name: "Leaf Green", value: "Leaf Green", image: "/data/games/leaf-green.png" },

  // Gen 4 (2006–2009)
  { name: "Diamond", value: "Diamond", image: "/data/games/diamond.png" },
  { name: "Pearl", value: "Pearl", image: "/data/games/pearl.png" },
  { name: "Platinum", value: "Platinum", image: "/data/games/platinum.png" },
  { name: "Heart Gold", value: "Heart Gold", image: "/data/games/heart-gold.png" },
  { name: "Soul Silver", value: "Soul Silver", image: "/data/games/soul-silver.png" },

  // Gen 5 (2010–2012)
  { name: "Black", value: "Black", image: "/data/games/black.png" },
  { name: "White", value: "White", image: "/data/games/white.png" },
  { name: "Black 2", value: "Black 2", image: "/data/games/black-2.png" },
  { name: "White 2", value: "White 2", image: "/data/games/white-2.png" },

  // Gen 6 (2013–2014)
  { name: "X", value: "X", image: "/data/games/x.png" },
  { name: "Y", value: "Y", image: "/data/games/y.png" },
  { name: "Omega Ruby", value: "Omega Ruby", image: "/data/games/omega-ruby.png" },
  { name: "Alpha Sapphire", value: "Alpha Sapphire", image: "/data/games/alpha-sapphire.png" },

  // Gen 7 (2016–2018)
  { name: "Sun", value: "Sun", image: "/data/games/sun.png" },
  { name: "Moon", value: "Moon", image: "/data/games/moon.png" },
  { name: "Ultra Sun", value: "Ultra Sun", image: "/data/games/ultra-sun.png" },
  { name: "Ultra Moon", value: "Ultra Moon", image: "/data/games/ultra-moon.png" },
  { name: "Let's Go Pikachu", value: "Let's Go Pikachu", image: "/data/games/lets-go-pikachu.png" },
  { name: "Let's Go Eevee", value: "Let's Go Eevee", image: "/data/games/lets-go-eevee.png" },

  // Gen 8 (2019–2021)
  { name: "Sword", value: "Sword", image: "/data/games/sword.png" },
  { name: "Shield", value: "Shield", image: "/data/games/shield.png" },
  { name: "Brilliant Diamond", value: "Brilliant Diamond", image: "/data/games/brilliant-diamond.png" },
  { name: "Shining Pearl", value: "Shining Pearl", image: "/data/games/shining-pearl.png" },
  { name: "Legends Arceus", value: "Legends Arceus", image: "/data/games/legends-arceus.png" },

  // Gen 9 (2022–2023)
  { name: "Scarlet", value: "Scarlet", image: "/data/games/scarlet.png" },
  { name: "Violet", value: "Violet", image: "/data/games/violet.png" },

  // Other
  { name: "GO", value: "GO", image: "/data/games/go.png" }
];

export const GAME_OPTIONS_TWO = [

  // Gen 1 (1996–1999)
  { name: "Red", value: "Red", image: "/data/games/red.png" },
  { name: "Blue", value: "Blue", image: "/data/games/blue.png" },
  { name: "Green", value: "Green", image: "/data/games/green.png" },
  { name: "Yellow", value: "Yellow", image: "/data/games/yellow.png" },

  // Gen 2 (1999–2001)
  { name: "Gold", value: "Gold", image: "/data/games/gold.png" },
  { name: "Silver", value: "Silver", image: "/data/games/silver.png" },
  { name: "Crystal", value: "Crystal", image: "/data/games/crystal.png" },

  // Gen 3 (2002–2006)
  { name: "Ruby", value: "Ruby", image: "/data/games/ruby.png" },
  { name: "Sapphire", value: "Sapphire", image: "/data/games/sapphire.png" },
  { name: "Emerald", value: "Emerald", image: "/data/games/emerald.png" },
  { name: "Fire Red", value: "Fire Red", image: "/data/games/fire-red.png" },
  { name: "Leaf Green", value: "Leaf Green", image: "/data/games/leaf-green.png" },

  // Gen 4 (2006–2009)
  { name: "Diamond", value: "Diamond", image: "/data/games/diamond.png" },
  { name: "Pearl", value: "Pearl", image: "/data/games/pearl.png" },
  { name: "Platinum", value: "Platinum", image: "/data/games/platinum.png" },
  { name: "Heart Gold", value: "Heart Gold", image: "/data/games/heart-gold.png" },
  { name: "Soul Silver", value: "Soul Silver", image: "/data/games/soul-silver.png" },

  // Gen 5 (2010–2012)
  { name: "Black", value: "Black", image: "/data/games/black.png" },
  { name: "White", value: "White", image: "/data/games/white.png" },
  { name: "Black 2", value: "Black 2", image: "/data/games/black-2.png" },
  { name: "White 2", value: "White 2", image: "/data/games/white-2.png" },

  // Gen 6 (2013–2014)
  { name: "X", value: "X", image: "/data/games/x.png" },
  { name: "Y", value: "Y", image: "/data/games/y.png" },
  { name: "Omega Ruby", value: "Omega Ruby", image: "/data/games/omega-ruby.png" },
  { name: "Alpha Sapphire", value: "Alpha Sapphire", image: "/data/games/alpha-sapphire.png" },

  // Gen 7 (2016–2018)
  { name: "Sun", value: "Sun", image: "/data/games/sun.png" },
  { name: "Moon", value: "Moon", image: "/data/games/moon.png" },
  { name: "Ultra Sun", value: "Ultra Sun", image: "/data/games/ultra-sun.png" },
  { name: "Ultra Moon", value: "Ultra Moon", image: "/data/games/ultra-moon.png" },
  { name: "Let's Go Pikachu", value: "Let's Go Pikachu", image: "/data/games/lets-go-pikachu.png" },
  { name: "Let's Go Eevee", value: "Let's Go Eevee", image: "/data/games/lets-go-eevee.png" },

  // Gen 8 (2019–2021)
  { name: "Sword", value: "Sword", image: "/data/games/sword.png" },
  { name: "Shield", value: "Shield", image: "/data/games/shield.png" },
  { name: "Brilliant Diamond", value: "Brilliant Diamond", image: "/data/games/brilliant-diamond.png" },
  { name: "Shining Pearl", value: "Shining Pearl", image: "/data/games/shining-pearl.png" },
  { name: "Legends Arceus", value: "Legends Arceus", image: "/data/games/legends-arceus.png" },

  // Gen 9 (2022–2023)
  { name: "Scarlet", value: "Scarlet", image: "/data/games/scarlet.png" },
  { name: "Violet", value: "Violet", image: "/data/games/violet.png" },

  // Other
  { name: "GO", value: "GO", image: "/data/games/go.png" }
];

// MARKS
export const MARK_OPTIONS = [
  { name: "None", value: "" },
  { name: "Absent-Minded Mark", value: "absent-minded", image: "/data/marks/mark-absent-minded.png" },
  { name: "Alpha Mark", value: "alpha", image: "/data/marks/mark-alpha.png" },
  { name: "Angry Mark", value: "angry", image: "/data/marks/mark-angry.png" },
  { name: "Blizzard Mark", value: "blizzard", image: "/data/marks/mark-blizzard.png" },
  { name: "Calmness Mark", value: "calmness", image: "/data/marks/mark-calmness.png" },
  { name: "Charismatic Mark", value: "charismatic", image: "/data/marks/mark-charismatic.png" },
  { name: "Cloudy Mark", value: "cloudy", image: "/data/marks/mark-cloudy.png" },
  { name: "Crafty Mark", value: "crafty", image: "/data/marks/mark-crafty.png" },
  { name: "Curry Mark", value: "curry", image: "/data/marks/mark-curry.png" },
  { name: "Dawn Mark", value: "dawn", image: "/data/marks/mark-dawn.png" },
  { name: "Destiny Mark", value: "destiny", image: "/data/marks/mark-destiny.png" },
  { name: "Dry Mark", value: "dry", image: "/data/marks/mark-dry.png" },
  { name: "Dusk Mark", value: "dusk", image: "/data/marks/mark-dusk.png" },
  { name: "Excited Mark", value: "excited", image: "/data/marks/mark-excited.png" },
  { name: "Ferocious Mark", value: "ferocious", image: "/data/marks/mark-ferocious.png" },
  { name: "Fishing Mark", value: "fishing", image: "/data/marks/mark-fishing.png" },
  { name: "Flustered Mark", value: "flustered", image: "/data/marks/mark-flustered.png" },
  { name: "Gourmand Mark", value: "gourmand", image: "/data/marks/mark-gourmand.png" },
  { name: "Humble Mark", value: "humble", image: "/data/marks/mark-humble.png" },
  { name: "Intellectual Mark", value: "intellectual", image: "/data/marks/mark-intellectual.png" },
  { name: "Intense Mark", value: "intense", image: "/data/marks/mark-intense.png" },
  { name: "Itemfinder Mark", value: "itemfinder", image: "/data/marks/mark-itemfinder.png" },
  { name: "Jittery Mark", value: "jittery", image: "/data/marks/mark-jittery.png" },
  { name: "Joyful Mark", value: "joyful", image: "/data/marks/mark-joyful.png" },
  { name: "Jumbo Mark", value: "jumbo", image: "/data/marks/mark-jumbo.png" },
  { name: "Kindly Mark", value: "kindly", image: "/data/marks/mark-kindly.png" },
  { name: "Lunchtime Mark", value: "lunchtime", image: "/data/marks/mark-lunchtime.png" },
  { name: "Mightiest Mark", value: "mightiest", image: "/data/marks/mark-mightiest.png" },
  { name: "Mini Mark", value: "mini", image: "/data/marks/mark-mini.png" },
  { name: "Misty Mark", value: "misty", image: "/data/marks/mark-misty.png" },
  { name: "Partner Mark", value: "partner", image: "/data/marks/mark-partner.png" },
  { name: "Peeved Mark", value: "peeved", image: "/data/marks/mark-peeved.png" },
  { name: "Prideful Mark", value: "prideful", image: "/data/marks/mark-prideful.png" },
  { name: "Pumped-Up Mark", value: "pumped-up", image: "/data/marks/mark-pumped-up.png" },
  { name: "Rainy Mark", value: "rainy", image: "/data/marks/mark-rainy.png" },
  { name: "Rare Mark", value: "rare", image: "/data/marks/mark-rare.png" },
  { name: "Rowdy Mark", value: "rowdy", image: "/data/marks/mark-rowdy.png" },
  { name: "Sandstorm Mark", value: "sandstorm", image: "/data/marks/mark-sandstorm.png" },
  { name: "Scowling Mark", value: "scowling", image: "/data/marks/mark-scowling.png" },
  { name: "Sleepy-Time Mark", value: "sleepy-time", image: "/data/marks/mark-sleepy-time.png" },
  { name: "Slump Mark", value: "slump", image: "/data/marks/mark-slump.png" },
  { name: "Smiley Mark", value: "smiley", image: "/data/marks/mark-smiley.png" },
  { name: "Snow Mark", value: "snow", image: "/data/marks/mark-snow.png" },
  { name: "Stormy Mark", value: "stormy", image: "/data/marks/mark-stormy.png" },
  { name: "Teary Mark", value: "teary", image: "/data/marks/mark-teary.png" },
  { name: "Thorny Mark", value: "thorny", image: "/data/marks/mark-thorny.png" },
  { name: "Titan Mark", value: "titan", image: "/data/marks/mark-titan.png" },
  { name: "Uncommon Mark", value: "uncommon", image: "/data/marks/mark-uncommon.png" },
  { name: "Unsure Mark", value: "unsure", image: "/data/marks/mark-unsure.png" },
  { name: "Upbeat Mark", value: "upbeat", image: "/data/marks/mark-upbeat.png" },
  { name: "Vigor Mark", value: "vigor", image: "/data/marks/mark-vigor.png" },
  { name: "Zero-Energy Mark", value: "zero-energy", image: "/data/marks/mark-zero-energy.png" },
  { name: "Zoned-Out Mark", value: "zoned-out", image: "/data/marks/mark-zoned-out.png" }
];

// METHODS (no icons needed, so keep as simple array)
export const METHOD_OPTIONS = [
  "",
  "Soft Resets",
  "Encounters",
  "Masuda",
  "Egg Hatching",
  "Poke Radar",
  "Chain Fishing",
  "Friend Safari",
  "Dex Nav",
  "Hordes",
  "SOS",
  "Poke Pelago",
  "Ultra Wormhole",
  "Catch Combo",
  "Battle Method",
  "Dynamax Adventures",
  "Max Raid/Raid Battles",
  "Grand Underground",
  "Massive Mass Outbreaks",
  "Picnic Resets",
  "Sandwich",
  "Found Randomly",
  "Research Rewards/Quests",
  "Time Space Distortions",
  "Gift Pokémon",
  "Fossil Revivals",
  "Mystery Gift"
];


export const genderForms = [
  "venusaur",
  "butterfree",
  "rattata",
  "raticate",
  "pikachu",
  "raichu",
  "zubat",
  "golbat",
  "gloom",
  "vileplume",
  "kadabra",
  "alakazam",
  "doduo",
  "dodrio",
  "hypno",
  "rhyhorn",
  "rhydon",
  "goldeen",
  "seaking",
  "scyther",
  "magikarp",
  "gyarados",
  "eevee",
  "meganium",
  "ledyba",
  "ledian",
  "xatu",
  "sudowoodo",
  "politoad",
  "aipom",
  "wooper",
  "quagsire",
  "murkrow",
  "wobbuffet",
  "girafarig",
  "gligar",
  "steelix",
  "scizor",
  "heracross",
  "sneasel",
  "ursaring",
  "piloswine",
  "octillery",
  "houndoom",
  "donphan",
  "torchic",
  "combusken",
  "blaziken",
  "beautifly",
  "dustox",
  "ludicolo",
  "nuzleaf",
  "shiftry",
  "meditite",
  "medicham",
  "roselia",
  "gulpin",
  "swalot",
  "numel",
  "camerupt",
  "cacturne",
  "milotic",
  "relicanth",
  "starly",
  "staravia",
  "staraptor",
  "bidoof",
  "bibarel",
  "kricketot",
  "kricketune",
  "shinx",
  "luxio",
  "luxray",
  "roserade",
  "combee",
  "pachirisu",
  "buizel",
  "floatzel",
  "ambipom",
  "gible",
  "gabite",
  "garchomp",
  "hippopotas",
  "hippowdon",
  "croagunk",
  "toxicroak",
  "finneon",
  "lumineon",
  "snover",
  "abomasnow",
  "weavile",
  "rhyperior",
  "tangrowth",
  "mamoswine",
  "unfezant",
  "frillish",
  "jellicent",
  "pyroar",
  "meowstic-male",
  "basculegion-male",
  "oinkologne-male",
  "indeedee-male"
];

export const specialFormLabels = {
  "pikachu-partner-cap": "Partner Cap",
  "deoxys-attack": "Attack Forme",
  "deoxys-defense": "Defense Forme",
  "deoxys-speed": "Speed Forme",
  "deoxys-normal": "Normal Forme",
  "burmy": "Plant Cloak",
  "burmy-sandy": "Sandy Cloak",
  "burmy-trash": "Trash Cloak",
  "wormadam-plant": "Plant Cloak",
  "wormadam-sandy": "Sandy Cloak",
  "wormadam-trash": "Trash Cloak",
  "shellos": "East Sea",
  "shellos-east": "West Sea",
  "gastrodon": "East Sea",
  "gastrodon-east": "West Sea",
  "rotom-heat": "Heat Form",
  "rotom-wash": "Wash Form",
  "rotom-frost": "Frost Form",
  "rotom-fan": "Fan Form",
  "rotom-mow": "Mow Form",
  "rotom": "Normal Form",
  "basculin-red-striped": "Red Stripe",
  "basculin-blue-striped": "Blue Stripe",
  "basculin-white-striped": "White Stripe",
  "deerling": "Spring Form",
  "deerling-summer": "Summer Form",
  "deerling-autumn": "Autumn Form",
  "deerling-winter": "Winter Form",
  "sawsbuck": "Spring Form",
  "sawsbuck-summer": "Summer Form",
  "sawsbuck-autumn": "Autumn Form",
  "sawsbuck-winter": "Winter Form",
  "flabebe": "Red Flower",
  "flabebe-yellow": "Yellow Flower",
  "flabebe-orange": "Orange Flower",
  "flabebe-blue": "Blue Flower",
  "flabebe-white": "White Flower",
  "floette": "Red Flower",
  "floette-yellow": "Yellow Flower",
  "floette-orange": "Orange Flower",
  "floette-blue": "Blue Flower",
  "floette-white": "White Flower",
  "florges": "Red Flower",
  "florges-yellow": "Yellow Flower",
  "florges-orange": "Orange Flower",
  "florges-blue": "Blue Flower",
  "florges-white": "White Flower",
  "furfrou": "Natural Form",
  "furfrou-heart": "Heart Trim",
  "furfrou-star": "Star Trim",
  "furfrou-diamond": "Diamond Trim",
  "furfrou-debutante": "Debutante Trim",
  "furfrou-matron": "Matron Trim",
  "furfrou-dandy": "Dandy Trim",
  "furfrou-la-reine": "La Reine Trim",
  "furfrou-kabuki": "Kabuki Trim",
  "furfrou-pharaoh": "Pharaoh Trim",
  "pumpkaboo-small": "Small Size",
  "pumpkaboo": "Average Size",
  "pumpkaboo-large": "Large Size",
  "pumpkaboo-super": "Super Size",
  "gourgeist-small": "Small Size",
  "gourgeist": "Average Size",
  "gourgeist-large": "Large Size",
  "gourgeist-super": "Super Size",
  "zygarde-10": "10% Forme",
  "zygarde-50": "50% Forme",
  "oricorio-baile": "Baile Style",
  "oricorio-pom-pom": "Pom-Pom Style",
  "oricorio-pau": "Pa'u Style",
  "oricorio-sensu": "Sensu Style",
  "lycanroc": "Midday Form",
  "lycanroc-midnight": "Midnight Form",
  "lycanroc-dusk": "Dusk Form",
  "minior-red-meteor": "Minior Form (Red)",
  "minior-orange-meteor": "Minior Form (Orange)",
  "minior-yellow-meteor": "Minior Form (Yellow)",
  "minior-green-meteor": "Minior Form (Green)",
  "minior-blue-meteor": "Minior Form (Blue)",
  "minior-indigo-meteor": "Minior Form (Indigo)",
  "minior-violet-meteor": "Minior Form (Violet)",
  "toxtricity": "Amped Form",
  "toxtricity-low-key": "Low Key Form",
  "sinistea": "Phony Form",
  "sinistea-antique": "Antique Form",
  "polteageist": "Phony Form",
  "polteageist-antique": "Antique Form",
  "maushold-family-of-three": "Family of Three",
  "maushold": "Family of Four",
  "squawkabilly-green-plumage": "Green Plumage",
  "squawkabilly-blue": "Blue Plumage",
  "squawkabilly-yellow": "Yellow Plumage",
  "squawkabilly-white": "White Plumage",
  "tatsugiri-curly": "Curly Form",
  "tatsugiri-droopy": "Droopy Form",
  "tatsugiri-stretchy": "Stretchy Form",
  "dudunsparce-three-segment": "Three-Segment Form",
  "dudunsparce": "Two-Segment Form",
  "poltchageist": "Counterfeit Form",
  "poltchageist-masterpiece": "Artisan Form",
  "sinistcha": "Counterfeit Form",
  "sinistcha-masterpiece": "Masterpiece Form",
  "burmy-sandy-alphaother": "Alpha Sandy",
  "burmy-trash-alphaother": "Alpha Trash",
  "wormadam-sandy-alphaother": "Alpha Sandy",
  "wormadam-trash-alphaother": "Alpha Trash",
  "shellos-alphaother": "Alpha West",
  "gastrodon-alphaother": "Alpha West",
  "rotom-heat-alphaother": "Alpha Heat",
  "rotom-wash-alphaother": "Alpha Wash",
  "rotom-frost-alphaother": "Alpha Frost",
  "rotom-fan-alphaother": "Alpha Fan",
  "rotom-mow-alphaother": "Alpha Mow",
  "shaymin-sky": "Sky Forme",
  "shaymin-land": "Land Forme",
  "landorus-incarnate": "Incarnate Forme",
  "tornadus-incarnate": "Incarnate Forme",
  "thundurus-incarnate": "Incarnate Forme",
  "enamorus-incarnate": "Incarnate Forme",
  "landorus-therian": "Therian Forme",
  "tornadus-therian": "Therian Forme",
  "thundurus-therian": "Therian Forme",
  "enamorus-therian": "Therian Forme",
  "urshifu-single-strike": "Single Strike Forme",
  "urshifu-rapid-strike": "Rapid Strike Forme",
  "vivillon-meadow": "Meadow Forme",
  "vivillon-archipelago": "Archipelago Forme",
  "vivillon-continental": "Continental Forme",
  "vivillon-elegant": "Elegant Forme",
  "vivillon-garden": "Garden Forme",
  "vivillon-high-plains": "High Plains Forme",
  "vivillon-icy-snow": "Icy Snow Forme",
  "vivillon-jungle": "Jungle Forme",
  "vivillon-marine": "Marine Forme",
  "vivillon-modern": "Modern Forme",
  "vivillon-monsoon": "Monsoon Forme",
  "vivillon-ocean": "Ocean Forme",
  "vivillon-polar": "Polar Forme",
  "vivillon-river": "River Forme",
  "vivillon-sandstorm": "Sandstorm Forme",
  "vivillon-savanna": "Savanna Forme",
  "vivillon-sun": "Sun Forme",
  "vivillon-tundra": "Tundra Forme",
  "vivillon-fancy": "Fancy Forme",
  "vivillon-pokeball": "Pokeball Forme",

};


export const specialCases = {

  "MAIN GRID!!!": "MAIN GRID!!!",
  "nidoran-m": "Nidoran ♂",
  "nidoran-f": "Nidoran ♀",
  "farfetchd": "Farfetch’d",
  "unown": "Unown A",
  "deoxys-normal": "Deoxys",
  "wormadam-plant": "Wormadam",
  "giratina-altered": "Giratina",
  "shaymin-land": "Shaymin",
  "basculin-red-striped": "Basculin",
  "tornadus-incarnate": "Tornadus",
  "thundurus-incarnate": "Thundurus",
  "landorus-incarnate": "Landorus",
  "keldeo-ordinary": "Keldeo",
  "meloetta-aria": "Meloetta",
  "meowstic-male": "Meowstic",
  "zygarde-50": "Zygarde",
  "oricorio-baile": "Oricorio",
  "wishiwashi-solo": "Wishiwashi",
  "minior-red-meteor": "Minior",
  "mimikyu-disguised": "Mimikyu",
  "sirfetchd": "Sirfetch’d",
  "mr-rime": "Mr. Rime",
  "eiscue-ice": "Eiscue",
  "indeedee-male": "Indeedee",
  "morpeko-full-belly": "Morpeko",
  "basculegion-male": "Basculegion",
  "enamorus-incarnate": "Enamorus",
  "oinkologne-male": "Oinkologne",
  "squawkabilly-green-plumage": "Squawkabilly",
  "tatsugiri-curly": "Tatsugiri",
  "wo-chien": "Wo-Chien",
  "chien-pao": "Chien-Pao",
  "ting-lu": "Ting-Lu",
  "chi-yu": "Chi-Yu",
  "mr-mime": "Mr. Mime",
  "mime-jr": "Mime Jr.",
  "type-null": "Type: Null",
  "jangmo-o": "Jangmo-o",
  "hakamo-o": "Hakamo-o",
  "kommo-o": "Kommo-o",
  "tapu-koko": "Tapu Koko",
  "tapu-lele": "Tapu Lele",
  "tapu-bulu": "Tapu Bulu",
  "tapu-fini": "Tapu Fini",
  "ho-oh": "Ho-Oh",
  "porygon-z": "Porygon-Z",
  "great-tusk": "Great Tusk",
  "iron-treads": "Iron Treads",
  "walking-wake": "Walking Wake",
  "iron-leaves": "Iron Leaves",
  "iron-valiant": "Iron Valiant",
  "roaring-moon": "Roaring Moon",
  "gimmighoul-roaming": "Gimmighoul",
  "gimmighoul": "Gimmighoul",
  "oinkologne-female": "Oinkologne",
  "urshifu-single-strike": "Urshifu",
  "urshifu-rapid-strike": "Urshifu",
  "vivillon-meadow": "Vivillon",

  "GENDER FORMS!!!": "GENDER FORMS!!!",
  "pikachu-gender": "Pikachu",
  "raichu-gender": "Raichu",
  "sneasel-hisui": "Sneasel",
  "frillish-female": "Frillish",
  "jellicent-female": "Jellicent",
  "meowstic-female": "Meowstic",
  "basculegion-female": "Basculegion",
  "indeedee-female": "Indeedee",

  "GMAX!!!": "GMAX!!!",
  "toxtricity-amped-gmax": "Toxtricity",
  "urshifu-single-strike-gmax": "Urshifu",
  "urshifu-rapid-strike-gmax": "Urshifu",

  "PALDEAN!!!": "PALDEAN!!!",
  "tauros-paldea-combat-breed": "Tauros",
  "tauros-paldea-blaze-breed": "Tauros",
  "tauros-paldea-aqua-breed": "Tauros",

  "OTHER!!!": "OTHER!!!",
  "pikachu-partner-cap": "Pikachu",
  "deoxys-attack": "Deoxys",
  "deoxys-defense": "Deoxys",
  "deoxys-speed": "Deoxys",
  "burmy-sandy": "Burmy",
  "burmy-trash": "Burmy",
  "wormadam-sandy": "Wormadam",
  "wormadam-trash": "Wormadam",
  "shellos-east": "Shellos",
  "gastrodon-east": "Gastrodon",
  "rotom-heat": "Rotom",
  "rotom-wash": "Rotom",
  "rotom-frost": "Rotom",
  "rotom-fan": "Rotom",
  "rotom-mow": "Rotom",
  "basculin-blue-striped": "Basculin",
  "basculin-white-striped": "Basculin",
  "deerling-summer": "Deerling",
  "deerling-autumn": "Deerling",
  "deerling-winter": "Deerling",
  "sawsbuck-summer": "Sawsbuck",
  "sawsbuck-autumn": "Sawsbuck",
  "sawsbuck-winter": "Sawsbuck",
  "flabebe-yellow": "Flabébé",
  "flabebe-orange": "Flabébé",
  "flabebe-blue": "Flabébé",
  "flabebe-white": "Flabébé",
  "floette-yellow": "Floette",
  "floette-orange": "Floette",
  "floette-blue": "Floette",
  "floette-white": "Floette",
  "florges-yellow": "Florges",
  "florges-orange": "Florges",
  "florges-blue": "Florges",
  "florges-white": "Florges",
  "furfrou-heart": "Furfrou",
  "furfrou-star": "Furfrou",
  "furfrou-diamond": "Furfrou",
  "furfrou-debutante": "Furfrou",
  "furfrou-matron": "Furfrou",
  "furfrou-dandy": "Furfrou",
  "furfrou-la-reine": "Furfrou",
  "furfrou-kabuki": "Furfrou",
  "furfrou-pharaoh": "Furfrou",
  "pumpkaboo-small": "Pumpkaboo",
  "pumpkaboo-large": "Pumpkaboo",
  "pumpkaboo-super": "Pumpkaboo",
  "gourgeist-small": "Gourgeist",
  "gourgeist-large": "Gourgeist",
  "gourgeist-super": "Gourgeist",
  "zygarde-10": "Zygarde",
  "oricorio-pom-pom": "Oricorio",
  "oricorio-pau": "Oricorio",
  "oricorio-sensu": "Oricorio",
  "lycanroc-midnight": "Lycanroc",
  "lycanroc-dusk": "Lycanroc",
  "minior-orange-meteor": "Minior",
  "minior-yellow-meteor": "Minior",
  "minior-green-meteor": "Minior",
  "minior-blue-meteor": "Minior",
  "minior-indigo-meteor": "Minior",
  "minior-violet-meteor": "Minior",
  "toxtricity-low-key": "Toxtricity",
  "sinistea-antique": "Sinistea",
  "polteageist-antique": "Polteageist",
  "maushold-family-of-three": "Maushold",
  "squawkabilly-blue": "Squawkabilly",
  "squawkabilly-yellow": "Squawkabilly",
  "squawkabilly-white": "Squawkabilly",
  "tatsugiri-droopy": "Tatsugiri",
  "tatsugiri-stretchy": "Tatsugiri",
  "dudunsparce-three-segment": "Dudunsparce",
  "sinistcha-masterpiece": "Sinistcha",
  "poltchageist-masterpiece": "Poltchageist",
  "shaymin-sky": "Shaymin",
  "landorus-therian": "Landorus",
  "tornadus-therian": "Tornadus",
  "thundurus-therian": "Thundurus",
  "enamorus-therian": "Enamorus",

  "VIVILLON!!!": "VIVILLON!!!",
  "vivillon-archipelago": "Vivillon",
  "vivillon-continental": "Vivillon",
  "vivillon-elegant": "Vivillon",
  "vivillon-garden": "Vivillon",
  "vivillon-high-plains": "Vivillon",
  "vivillon-icy-snow": "Vivillon",
  "vivillon-jungle": "Vivillon",
  "vivillon-marine": "Vivillon",
  "vivillon-modern": "Vivillon",
  "vivillon-monsoon": "Vivillon",
  "vivillon-ocean": "Vivillon",
  "vivillon-polar": "Vivillon",
  "vivillon-river": "Vivillon",
  "vivillon-sandstorm": "Vivillon",
  "vivillon-savanna": "Vivillon",
  "vivillon-sun": "Vivillon",
  "vivillon-tundra": "Vivillon",
  "vivillon-fancy": "Vivillon",
  "vivillon-pokeball": "Vivillon",

  "ALPHA!!!": "ALPHA!!!",
  "unown-alpha": "Unown A",
  "basculin-white-striped-alpha": "Basculin",
  "basculegion-male-alpha": "Basculegion",
  "basculegion-female-alpha": "Basculegion",
  "wormadam-plant-alpha": "Wormadam",

  "ALPHA OTHER!!!": "ALPHA OTHER!!!",
  "burmy-sandy-alphaother": "Burmy",
  "burmy-trash-alphaother": "Burmy",
  "wormadam-sandy-alphaother": "Wormadam",
  "wormadam-trash-alphaother": "Wormadam",
  "rotom-heat-alphaother": "Rotom",
  "rotom-wash-alphaother": "Rotom",
  "rotom-frost-alphaother": "Rotom",
  "rotom-fan-alphaother": "Rotom",
  "rotom-mow-alphaother": "Rotom",
};